#!/bin/sh
set -e

case "$1" in
  remove|upgrade|deconfigure)
    systemctl stop permafrost permafrost-relay 2>/dev/null || true
    systemctl disable permafrost permafrost-relay 2>/dev/null || true
    ;;
esac

#DEBHELPER#
